### ISSUE TITLE
How to use AnyCallable? What exactly is "state template instance function"?

### ISSUE THREAD

**Issue by adamryczkowski** [thecppzoo/zoo#9]
Hi,

The Arduino embedded platform supports c++11 compiler, but it lacks implementation of `<functional>`, which is a big shame, because `std::functional` is something very useful. Especially for interchangeable stateless and stateful event handlers (the latter implemented e.g. using capturing lambdas).

I talked to Eduardo Madrid at the last cppcon in Denver and he advertised me this library's `AnyCallable` class. Unfortunately the dependency tree for `zoo::function` is 7 other header files, besides the fact I did not manage to compile them anyway.

Do you know if  `AnyCallable` is usable as it is now? If so, can you help me with a toy usage example? If not, can you point me to some lightweight re-implementation of `std::function` that covers at least function pointers and lambdas?

Thank you

**Comment by adamryczkowski** [comment]
I found an alternative solution: http://brnz.org/hbr/?p=1767 .

**Comment by thecppzoo** [comment]
Hello, thanks for the explanation about Arduino.
The way to use `AnyCallable` is for example to use it through the direct replacement of `std::function` implemented in the typedef `zoo::function` available in [`function.h`](https://github.com/thecppzoo/zoo/blob/master/inc/zoo/function.h)
You may look at comprehensive test cases at here: [`AnyCallable.cpp`](https://github.com/thecppzoo/zoo/blob/master/test/AnyCallable.cpp), which uses the Catch2 framework which is very easy to learn.  The build system uses CMake, and the tests use TravisCI for continuous integration.  We are *very* confident this component works.
In the documentation (markdown files of design, etc) it is explained some of the code conventions and the design of this component.
You can change `AnyCallable.h` to remove the inclusion to `function` and as far as I can tell, the only use is to bring in `bad_function_call`, [here](https://github.com/thecppzoo/zoo/blob/bbab9d2ef2db148945f670b6e32ac2e83767fd6e/inc/zoo/AnyCallable.h#L117) which according to the standard needs to be called when the trampoline is invoked but does not contain a target.
I am Eduardo, nice to say hello to you.
